export const AssetLibraryEntities = [
    {
        id: 'rimuru_pack1',
        spriteKey: 'rimuru',
        name: 'Rimuru (Pack 1 - Classic)',
        category: 'Player (Default)',
        title: 'Great Demon Lord / Predator Slime',
        lore: 'The original hand-crafted 16x16 / 32x16 pixel art slime with crescent water slashes, hydro hammer, gluttony barrier, black flame, and megiddo.',
        hp: '100 - 300',
        atk: '10 - 45',
        def: '8 - 25',
        speed: '200 px/s',
        animations: ['idle', 'walk', 'run', 'jump', 'attack_light', 'attack_heavy', 'special', 'water_blade', 'barrier', 'black_flame', 'megiddo', 'predator', 'hurt', 'death', 'victory'],
        forcePack: 1,
        tint: null
    },
    {
        id: 'rimuru_pack2',
        spriteKey: 'rimuru',
        name: 'Rimuru (Pack 2 - HD Arcade)',
        category: 'Player (Remastered)',
        title: 'High-Res Gelatinous Predator',
        lore: 'Remastered high-resolution arcade pixel art with elastic squash-and-stretch bounce, large crescent scythe slashes, anvil hammer, and vortex vacuum.',
        hp: '100 - 300',
        atk: '10 - 45',
        def: '8 - 25',
        speed: '200 px/s',
        animations: ['idle', 'run', 'jump', 'attack_light', 'attack_heavy', 'special', 'water_blade', 'barrier', 'black_flame', 'megiddo', 'predator', 'hurt', 'death', 'victory'],
        forcePack: 2,
        tint: null
    },
    {
        id: 'goblin_archer_p1',
        spriteKey: 'goblin_archer',
        name: 'Goblin Sharpshooter (Pack 1)',
        category: 'Ranged Enemy',
        title: 'Bone-Bow Poison Sniper (Default)',
        lore: 'Remastered marksman on a strict 16:9 grid with locked anatomical scale, high-tension bow draw, and toxic green arrow streak projectile.',
        hp: '25',
        atk: '10',
        def: '2',
        speed: '110 px/s',
        animations: ['idle', 'run', 'attack', 'hurt', 'death'],
        forcePack: 1,
        tint: null
    },
    {
        id: 'goblin_archer_p2',
        spriteKey: 'goblin_archer',
        name: 'Goblin Sharpshooter (Pack 2)',
        category: 'Ranged Enemy',
        title: 'Bone-Bow Marksman (Variant)',
        lore: 'Alternative hooded goblin marksman variant with extended draw animations and green venom aura.',
        hp: '25',
        atk: '10',
        def: '2',
        speed: '110 px/s',
        animations: ['idle', 'run', 'attack', 'hurt', 'death'],
        forcePack: 2,
        tint: null
    },
    {
        id: 'goblin_pack1',
        spriteKey: 'goblin',
        name: 'Goblin Scout (Pack 1)',
        category: 'Melee Grunt',
        title: 'Forest Dagger Marauder (Classic)',
        lore: 'Classic quick-footed forest goblins equipped with steel daggers. Patrols caverns in packs and lunges with rapid slashes.',
        hp: '30',
        atk: '8',
        def: '2',
        speed: '120 px/s',
        animations: ['idle', 'run', 'attack', 'hurt', 'death'],
        forcePack: 1,
        tint: null
    },
    {
        id: 'goblin_pack2',
        spriteKey: 'goblin',
        name: 'Goblin Scout (Pack 2)',
        category: 'Melee Grunt',
        title: 'Overhauled Dagger Assassin (New)',
        lore: 'Remastered goblin marauder on a strict 16:9 grid with exaggerated 4-frame run cycle, high leaping plunge attack, and locked anatomy scale.',
        hp: '30',
        atk: '8',
        def: '2',
        speed: '120 px/s',
        animations: ['idle', 'run', 'attack', 'hurt', 'death'],
        forcePack: 2,
        tint: null
    },
    {
        id: 'serpent_pack1',
        spriteKey: 'serpent',
        name: 'Tempest Serpent (Pack 1)',
        category: 'Mythic Boss',
        title: 'Giant Black Cavern Serpent (Classic / 黒蛇)',
        lore: 'Colossal serpentine predator ruler of the Sealed Caverns. Commands crackling electric thunderhorns, crushing jaws, and lethal venom torrents.',
        hp: '300',
        atk: '25',
        def: '20',
        speed: '80 px/s',
        animations: ['idle', 'run', 'attack', 'hurt', 'death'],
        forcePack: 1,
        tint: null
    },
    {
        id: 'serpent_pack2',
        spriteKey: 'serpent',
        name: 'Tempest Serpent (Pack 2)',
        category: 'Mythic Boss',
        title: 'Giant Tempest Serpent (Apex Predator / 黒蛇)',
        lore: 'Remastered high-resolution Black Serpent with locked anatomy scale, charged electric thunderhorn pulses, noxious venom breath, and crushing subterranean coils.',
        hp: '300',
        atk: '25',
        def: '20',
        speed: '80 px/s',
        animations: ['idle', 'run', 'attack', 'hurt', 'death'],
        forcePack: 2,
        tint: null
    },
    {
        id: 'tiles_moss',
        spriteKey: 'tiles',
        name: 'Ancient Cavern Tileset',
        category: 'Environment Tiles',
        title: 'Modular Moss-Stone & Scaffolding',
        lore: 'Modular 16-bit ancient masonry overgrown with lush emerald moss, floating wood-and-moss ledges, subterranean rope bridges, vertical crags, and ionic pillars.',
        hp: 'Solid',
        atk: 'N/A',
        def: 'Infinite',
        speed: 'Static',
        animations: ['ground_mid', 'ground_left', 'ground_right', 'plat_mid', 'plat_left', 'plat_right', 'bridge', 'wall_left', 'wall_right', 'ceiling', 'underhang', 'slope_up', 'slope_down', 'pillar_top', 'pillar_base'],
        forcePack: null,
        tint: null
    },
    {
        id: 'magisteel_ore',
        spriteKey: 'magisteel',
        name: 'Magisteel Ore Deposit',
        category: 'Breakable Mineral',
        title: 'Luminescent Mana Crystal Vein',
        lore: 'High-purity magical ore cluster charged with raw magicules. Pulses with radiant cyan energy and shatters into sparkling mineral shards when harvested.',
        hp: '15 (Breakable)',
        atk: '0',
        def: '5',
        speed: 'Static',
        animations: ['idle', 'break'],
        forcePack: null,
        tint: null
    },
    {
        id: 'hipokute_herb',
        spriteKey: 'hipokute',
        name: 'Hipokute Healing Lotus',
        category: 'Magical Flora',
        title: 'Subterranean Herb of Restoration',
        lore: 'A rare subterranean flora blooming with vibrant violet petals and restorative healing motes. Used by Rimuru to brew high-potency recovery potions.',
        hp: 'Flora',
        atk: 'Heal +50 HP',
        def: '0',
        speed: 'Sway',
        animations: ['bloom'],
        forcePack: null,
        tint: null
    },
    {
        id: 'runic_monolith',
        spriteKey: 'monolith',
        name: 'Ancient Runic Monolith',
        category: 'Runic Relic',
        title: 'Sanctuary Gate Pillar',
        lore: 'A carved stone obelisk engraved with ancient dwarven/dragon runes. Ignites with celestial light and a levitating runic halo to reveal hidden chambers.',
        hp: 'Indestructible',
        atk: 'Mana Surge',
        def: 'Infinite',
        speed: 'Static',
        animations: ['activate'],
        forcePack: null,
        tint: null
    },
    {
        id: 'warp_portal',
        spriteKey: 'portal',
        name: 'Dimensional Warp Portal',
        category: 'Gateway Arch',
        title: 'Dragon Arch Spatial Vortex',
        lore: 'Ancient dragon-crested stone gateway housing a rotating cosmic blue-violet singularity that warps players across cavern floors and boss arenas.',
        hp: 'Spatial Rift',
        atk: 'Warp Entry',
        def: 'Infinite',
        speed: 'Continuous Vortex',
        animations: ['idle', 'activate'],
        forcePack: null,
        tint: null
    },
    {
        id: 'treasure_chest',
        spriteKey: 'chest',
        name: 'Gilded Treasure Chest',
        category: 'Interactive Loot',
        title: 'Ancient Dwarven Relic Cache',
        lore: 'Ironwood chest bound with forged gold filigree and sapphire rune lock. Opens to bestow gold bullion, rare gems, and restorative elixir potions.',
        hp: 'Interact [E]',
        atk: 'Loot Drop',
        def: 'Rune Locked',
        speed: 'Static',
        animations: ['open'],
        forcePack: null,
        tint: null
    },
    {
        id: 'clay_urn',
        spriteKey: 'urn',
        name: 'Ancient Clay Urn',
        category: 'Destructible Prop',
        title: 'Sealed Potion Vessel',
        lore: 'Terracotta jar sealed with enchanted red wax. Shatters into ceramic shards on impact, dropping silver coins and health orbs.',
        hp: '1 Hit',
        atk: '0',
        def: '0',
        speed: 'Static',
        animations: ['break'],
        forcePack: null,
        tint: null
    },
    {
        id: 'dragon_torch',
        spriteKey: 'torch',
        name: 'Dragon Wall Torch',
        category: 'Atmosphere Lighting',
        title: 'Carved Sconce Flame',
        lore: 'Wall-mounted iron dragon sconce burning with everlasting magical flame, casting dancing orange light and embers across damp dungeon stones.',
        hp: 'Fixture',
        atk: 'Illumination',
        def: 'Infinite',
        speed: 'Flame Dance',
        animations: ['burn'],
        forcePack: null,
        tint: null
    },
    {
        id: 'rest_campfire',
        spriteKey: 'campfire',
        name: 'Adventurer Campfire',
        category: 'Sanctuary Rest',
        title: 'Hearthfire Sanctuary Site',
        lore: 'A crackling stone-ringed hearth that restores stamina, clears poison status ailments, and saves cavern checkpoint progression.',
        hp: 'Checkpoint',
        atk: 'Regeneration',
        def: 'Infinite',
        speed: 'Flame Flickering',
        animations: ['burn'],
        forcePack: null,
        tint: null
    },
    {
        id: 'floor_spikes',
        spriteKey: 'spikes',
        name: 'Razor Floor Spikes',
        category: 'Lethal Trap',
        title: 'Spring-Loaded Impaler Plate',
        lore: 'Concealed stone floor plate loaded with razor-sharp tempered steel spikes that erupt upward when stepped on by intruders.',
        hp: 'Hazard',
        atk: '18 Direct DMG',
        def: 'Trap',
        speed: 'Spring-Loaded',
        animations: ['trigger'],
        forcePack: null,
        tint: null
    },
    {
        id: 'ceiling_stalactite',
        spriteKey: 'stalactite',
        name: 'Ceiling Drop Stalactite',
        category: 'Overhead Hazard',
        title: 'Quake Triggered Drop Spire',
        lore: 'Massive stone stalactite hanging from the cavern ceiling. Trembles upon hearing combat tremors before plunging to shatter on the floor.',
        hp: 'Hazard',
        atk: '25 Heavy Impact',
        def: 'Breakable on Floor',
        speed: 'Terminal Gravity',
        animations: ['drop'],
        forcePack: null,
        tint: null
    },
    {
        id: 'toxic_spore_shroom',
        spriteKey: 'spore_shroom',
        name: 'Toxic Spore Mushroom',
        category: 'Bio Hazard',
        title: 'Poison Spore Geyser',
        lore: 'Bulbous mutant toadstool that inflates and detonates with a concentrated green poison gas geyser containing lingering skull toxins.',
        hp: 'Hazard',
        atk: 'Poison Status DOT',
        def: 'Elastic Cap',
        speed: 'Eruptive',
        animations: ['spore'],
        forcePack: null,
        tint: null
    },
    {
        id: 'acid_swamp_vent',
        spriteKey: 'acid_vent',
        name: 'Acid Bubble Vent',
        category: 'Corrosive Hazard',
        title: 'Cavern Swamp Fissure',
        lore: 'Subterranean green acid pool with expanding sulfurous bubbles that burst into caustic spray, melting armor and slowing mobility.',
        hp: 'Hazard',
        atk: 'Acid Burn + Slow',
        def: 'Liquid Pool',
        speed: 'Bubbling',
        animations: ['bubble'],
        forcePack: null,
        tint: null
    },
    {
        id: 'water_blade_vfx',
        spriteKey: 'water_blade_proj',
        name: 'Water Blade (水刃 — VFX)',
        category: 'Special Skill VFX',
        title: 'Pressurized Crescent Hydro Cutter',
        lore: 'High-speed spinning crescent blade of condensed pressurized water magic. Features a razor-sharp white-hot cutting edge and hydrodynamic spray droplets.',
        hp: 'Projectile',
        atk: '35 (Piercing)',
        def: 'N/A',
        speed: '580 px/s',
        animations: ['idle'],
        forcePack: null,
        tint: null
    },
    {
        id: 'gluttony_barrier_vfx',
        spriteKey: 'barrier_vfx',
        name: 'Gluttony Barrier (水防壁 — VFX)',
        category: 'Special Skill VFX',
        title: '360° Runic Hexagonal Forcefield',
        lore: 'A rotating concentric hexagonal forcefield of pure aqua magicules, inscribed with ancient draconic runes and shielded by 3 orbiting light magisferes.',
        hp: '2.0s Invulnerability',
        atk: 'Reflects Projectiles',
        def: 'Complete Immunity',
        speed: 'Orbiting Rotation',
        animations: ['idle'],
        forcePack: null,
        tint: null
    },
    {
        id: 'black_flame_vfx',
        spriteKey: 'black_flame_vfx',
        name: 'Black Flame Burst (黒炎 — VFX)',
        category: 'Special Skill VFX',
        title: 'Demonic Hellfire Nova & Lightning',
        lore: 'An explosive radial burst of dark-violet and amethyst demonic hellfire, discharging crackling purple lightning arcs and massive ground-clearing shockwaves.',
        hp: 'Instant AoE',
        atk: '60 (Explosive)',
        def: 'N/A',
        speed: 'Radial Burst',
        animations: ['idle'],
        forcePack: null,
        tint: null
    },
    {
        id: 'megiddo_beam_vfx',
        spriteKey: 'megiddo_beam_vfx',
        name: 'Megiddo: Rain of Light (神之怒 — VFX)',
        category: 'Special Skill VFX',
        title: 'Celestial Solar Optic Laser Pillar',
        lore: 'A searing vertical pillar of focused celestial solar energy descending from high above, terminating in a blinding white core and expanding ground crater shockwaves.',
        hp: 'Supreme Execution',
        atk: '100 (True Holy)',
        def: 'N/A',
        speed: 'Orbital Strike',
        animations: ['idle'],
        forcePack: null,
        tint: null
    }
];
